In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import pandas_profiling as pp

## Loading dataset

In [2]:
!ls -al

total 7248
drwxrwxr-x 8 jovyan  1000    4096 Mar 11 17:54  .
drwxr-xr-x 1 root   root     4096 Feb 14 16:11  ..
drwxr-xr-x 4 jovyan users    4096 Mar 11 17:50  .cache
drwxr-xr-x 3 jovyan users    4096 Mar 11 17:48  .config
-rw-r--r-- 1 jovyan users    1431 Mar 11 17:51  dataset_reporting.ipynb
drwxrwxr-x 8 jovyan  1000    4096 Mar 11 17:55  .git
-rw-r--r-- 1 jovyan users  563091 Mar 11 17:54 'Hackathon Amber 110319.pptx'
-rw-r--r-- 1 jovyan users  973701 Mar 11 17:54 'Hackathon Amber.zip'
drwxr-xr-x 2 jovyan users    4096 Mar 11 17:47  .ipynb_checkpoints
drwxr-xr-x 5 jovyan users    4096 Mar 11 17:47  .ipython
drwxr-xr-x 3 jovyan users    4096 Mar 11 17:40  .local
-rw-rw-r-- 1 jovyan  1000      15 Mar 11 17:36  README.md
-rw-r--r-- 1 jovyan users   11106 Mar 11 17:54  sample_solutions.csv
-rw-r--r-- 1 jovyan users 5828094 Mar 11 17:54  train.csv

In [5]:
!head sample_solutions.csv

In [4]:
!head train.csv

In [6]:
df = pd.read_csv("train.csv", delimiter=";")

In [8]:
df.sample(5).T

,29340,15944,9735,33114,13109
id,29341,15945,9736,33115,13110
year,2018,2018,2018,2018,2018
month,10,8,7,11,7
day,27,12,8,18,27
day_part,4,4,3,2,3
start_hub_id,cc6eead4-9f17-4344-8e14-4df8d2be35a5,b8e69830-2432-476c-8deb-686194b27434,cc6eead4-9f17-4344-8e14-4df8d2be35a5,f7e56e86-8993-4cbd-a471-519da9027580,6b3ceafc-f10f-46a3-a5b0-6c86e95a3a68
weekday,6,0,0,0,5
week,43,32,27,46,30
checkouts,0,0,0,0,0
reservations,0,0,0,0,0
checkout_min12h,0,0,0,0,0
checkout_min24h,0,0,0,0,0
checkout_min1w,0,0,0,0,0
checkout_min2w,0,0,0,0,0
checkout_min3w,0,0,0,0,0
checkout_min4w,0,0,0,0,0
temp,4,"20,75","24,5",2,"34,5"
rain,0,0,0,0,0
is_holiday,False,False,False,False,False
holidays_in_week,0,0,0,0,0
zuid_school,False,True,True,False,True
midden_school,True,True,False,False,True
noord_school,True,True,False,False,True

In [9]:
# advanced way for df.describe()
pp.ProfileReport(df).to_file('report.html')

In [1]:
help(tsfresh)

NameError: name 'tsfresh' is not defined